### ISSUE TITLE
Jeepers! We have no main class

### ISSUE THREAD

**Issue by ThePatrickBrady** [Eastside-Catholic/Tutorial#1]
This is bad in case people try to open and use the tutorial repository. We should add a main method.

**Comment by ThePatrickBrady** [comment]
Im on the job

**Comment by ThePatrickBrady** [comment]
ok, i think i did it, verifying before closing issue

**Comment by ThePatrickBrady** [comment]
Looks like the issue has been fixed. Closing and locking the issue.

**Comment by FirePieman** [comment]
k
